server:
  port: 8001
  servlet:
    context-path: /member

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.128:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  config: classpath:logback.xml
  level:
    com.spongzi.train: trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
