server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
      routes:
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/**