server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
      routes:
        - id: member
          uri: http://localhost:8001
          predicates:
            - Path=/member/**